#!/bin/bash

set -x

set -eo pipefail

# Use odo v1.0.1
# ----------------
curl -kLs https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.0.1/odo-linux-amd64 -o /opt/app-root/bin/odo-v1.0.1
chmod 755 /opt/app-root/bin/odo-v1.0.1

/opt/app-root/bin/odo-v1.0.1 preference set UpdateNotification false
