#!/bin/bash

set -x

set -eo pipefail

export ODO_VERSION=latest

# Use odo v1.1.0
# ----------------
curl -o odo.tar.gz -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/$ODO_VERSION/odo-linux-amd64.tar.gz && \
    tar -xvf odo.tar.gz && \
    rm -f odo.tar.gz && \
    mv odo /usr/bin/odo && \
    chmod +x /usr/bin/odo