#!/bin/bash

set -x

set -eo pipefail

# Use odo v1.1.0
# ----------------
curl -kLs https://mirror.openshift.com/pub/openshift-v4/clients/odo/v1.1.0/odo-linux-amd64 -o /opt/app-root/bin/odo-v1.1.0
chmod 755 /opt/app-root/bin/odo-v1.1.0

/opt/app-root/bin/odo-v1.1.0 preference set UpdateNotification false
