WORKSHOP_NAME=odo
WORKSHOP_IMAGE=quay.io/openshiftlabs/lab-developing-with-odo:2.0
WORKSHOP_TITLE="Developing applications with odo"
WORKSHOP_DESCRIPTION="Developing applications with odo"
WORKSHOP_MEMORY=512Mi
AUTH_USERNAME=workshop
AUTH_PASSWORD=workshop
SPAWNER_MODE=learning-portal
RESOURCE_BUDGET=x-large
MAX_SESSION_AGE=3600
IDLE_TIMEOUT=300
