#!/bin/bash

set -x

set -eo pipefail

if [ x"$PROJECT_NAMESPACE" != x"" ]; then
    # TODO: Change back to view once the issue is solved
    oc policy add-role-to-user edit -z default -n "$PROJECT_NAMESPACE" || true
fi
