#!/bin/bash

set -x

set -eo pipefail

# Use odo v1.0.0-beta1
# ----------------
curl -kLs https://github.com/openshift/odo/releases/download/v1.0.0-beta1/odo-linux-amd64 -o /opt/app-root/bin/odo-latest
chmod 755 /opt/app-root/bin/odo-latest
# ----------------

odo utils config set UpdateNotification false

if [ x"$PROJECT_NAMESPACE" != x"" ]; then
    # TODO: Change back to view once the issue is solved
    oc policy add-role-to-user edit -z default -n "$PROJECT_NAMESPACE" || true
fi
